sonar.projectKey=netflix-clone
sonar.projectName=Netflix Clone
sonar.projectVersion=1.0

# Source directory
sonar.sources=src

# Exclude node_modules and build
sonar.exclusions=node_modules/**,build/**,dist/**

# Language settings
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Optional for better analysis
sonar.sourceEncoding=UTF-8
